### ISSUE TITLE
Channel Attention

### ISSUE THREAD

**Issue by Polaris231** [liyunsheng13/DRT#2]
![image](https://user-images.githubusercontent.com/58073043/118480450-d8546200-b744-11eb-8c68-52ef399d2d72.png)
![image](https://user-images.githubusercontent.com/58073043/118481445-143bf700-b746-11eb-9ad2-8bd992b29406.png)
Hello! In the code you published, I only found the Subspace Routing module, could you please tell me where the Channel Attention module is? And  in the ImageNet pre-trained model, I find the conv_u and bn_u that the model don't have.

**Comment by liyunsheng13** [comment]
Hi

Since the best result I achieved in the paper is only based on subspace routing, I only clear and release the code for this block. For the pre-trained model, it contains some unused layers e.g. conv_u, bn_u that I should have removed before I release the code. Thanks a lot for letting me know and I will upload a new model later on. But at this moment, I think it won't cause an error when you load the model, right?

**Comment by Polaris231** [comment]
Thanks for your reply!  I got it. And it's right, there is no errors occur when I load the model. In the end, Could you have other versions of resnet for pre-trained model  in the ImageNet?

**Comment by liyunsheng13** [comment]
No, I have tried ResNet-50, since ResNet-101 is more generally used for the DomainNet dataset. But if you need it, I can try to train it.

**Comment by e96031413** [comment]
Hi @liyunsheng13 , I am curious about how to get the model pre-trained in the ImageNet? e.g. ResNet18
Since the parameter and FLOPs is quite big for edge devices, If we can deploy smaller DRT model on the edge devices, it will have great potential for industry to handle such domain shift problem.

**Comment by liyunsheng13** [comment]
I just pretrained DRT same as the standard training process of ResNet. All you need to do is to add the dynamic residual to each conv layer and then train the network with ImageNet dataset with same hyperparameters. Please let me know if you have any other questions.

**Comment by e96031413** [comment]
Hi @liyunsheng13, Thanks for your reply. I have 2 questions.

**Q1:** Does "train the network with ImageNet dataset" means training with the source code in this repo?
or shoud I use other source code for training on ImageNet. Such as [this one](https://github.com/pytorch/examples/tree/master/imagenet)?

**Q2:** I found there are two ResClassifier(F1 and F2) in drt.py. My assumption is that even training with the ImageNet dataset, we should still use F1 and F2 as classifier, right?

**Comment by liyunsheng13** [comment]
For Q1, you can use any source code to train ResNet. I do not upload the code for this part but I think the one you sent is fine.

For Q2, when you train ResNet with ImageNet, you do not need to add F1 and F2 since the two classifiers are used to do domain alignment and there is no need to initialize them.

**Comment by e96031413** [comment]
@liyunsheng13 Thanks for your detailed explanation.

I just add the dynamic residual to the BasicBlock of ResNet to create the ResNet18 version.

Following is my implementation:

I get the following class BasicBlock from [here](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py) and modify the code as you implemented in [model/resnet_dra.py](https://github.com/liyunsheng13/DRT/blob/main/model/resnet_dra.py) but I directly use it inside the BasicBlock.

```python
class BasicBlock(nn.Module):
    expansion: int = 1

    def __init__(
        self,
        inplanes: int,
        planes: int,
        stride: int = 1,
        downsample: Optional[nn.Module] = None,
        groups: int = 1,
        base_width: int = 64,
        dilation: int = 1,
        norm_layer: Optional[Callable[..., nn.Module]] = None
    ) -> None:
        super(BasicBlock, self).__init__()
        if norm_layer is None:
            norm_layer = nn.BatchNorm2d
        if groups != 1 or base_width != 64:
            raise ValueError('BasicBlock only supports groups=1 and base_width=64')
        if dilation > 1:
            raise NotImplementedError("Dilation > 1 not supported in BasicBlock")
        # Both self.conv1 and self.downsample layers downsample the input when stride != 1
        self.conv1 = conv3x3(inplanes, planes, stride)
        self.bn1 = norm_layer(planes)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = conv3x3(planes, planes)
        self.bn2 = norm_layer(planes)
        self.downsample = downsample
        self.stride = stride
        inp, oup = inplanes, planes * 4
        self.squeeze = inp // 16
        self.dim = int(math.sqrt(inp))
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.fc = nn.Sequential(
            nn.Linear(inp, self.squeeze, bias=False),
            nn.ReLU(inplace=True),
            nn.Linear(self.squeeze, 4, bias=False),
        )
        self.sf = nn.Softmax(dim=1)
        self.conv_s1 = nn.Conv2d(planes, planes, 1, stride=stride, padding=0, bias=False)
        self.conv_s2 = nn.Conv2d(planes, planes, 1, stride=stride, padding=0, bias=False)
        self.conv_s3 = nn.Conv2d(planes, planes, 1, stride=stride, padding=0, bias=False)
        self.conv_s4 = nn.Conv2d(planes, planes, 1, stride=stride, padding=0, bias=False)
        
    def forward(self, x):
        b, c, h, w = x.size()
        y = self.fc(self.avg_pool(x).view(b, c)).view(b, 4, 1, 1, 1)
        y = self.sf(y)
        
        identity = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)
        
        dyres = self.conv_s1(out)*y[:,0] + self.conv_s2(out)*y[:,1] + \
            self.conv_s3(out)*y[:,2] + self.conv_s4(out)*y[:,3]

        out = dyres + self.conv2(out)
        out = self.bn2(out)

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
        out = self.relu(out)

        return out

def resnet18(pretrained: bool = False, progress: bool = True, **kwargs: Any) -> ResNet:
    return _resnet('resnet18', BasicBlock, [2, 2, 2, 2], pretrained, progress,
                   **kwargs)
```
Durining the training stage, the following error occurs:
```
Traceback (most recent call last):
  File "main.py", line 433, in <module>
    main()
  File "main.py", line 113, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 249, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "main.py", line 294, in train
    output = model(images)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/notebooks/nfs/work/yanwei.liu/ImageNetTraining/resnet_dra.py", line 314, in forward
    return self._forward_impl(x)
  File "/root/notebooks/nfs/work/yanwei.liu/ImageNetTraining/resnet_dra.py", line 303, in _forward_impl
    x = self.layer2(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/notebooks/nfs/work/yanwei.liu/ImageNetTraining/resnet_dra.py", line 139, in forward
    out = dyres + self.conv2(out)
RuntimeError: The size of tensor a (14) must match the size of tensor b (28) at non-singleton dimension 3
```
I use pdb to trace the code, and here is the size of dyres and self.conv2(out)
```bash
(Pdb) dyres.size()
torch.Size([128, 128, 14, 14])
(Pdb) self.conv2(out).size()
torch.Size([128, 128, 28, 28])
```

Do you know how to modify the implementation in my BasicBlock to avoid the dimension error?

I also notice that there is a variable "expansion=1" in the BasicBlock(for ResNet18 and ResNet34), and "expansion=4" in the Bottleneck(for ResNet 50 and ResNet101). Is this error related to the variable "expansion"?

**Comment by e96031413** [comment]
Hello, I just solved the dimension problem

here is the code:
```
import torch
from torch import Tensor
import torch.nn as nn
from torchvision.models.utils import load_state_dict_from_url
from torch.autograd import Function
import torch.nn.functional as F
import math
from typing import Type, Any, Callable, Union, List, Optional


__all__ = ['ResNet', 'resnet18', 'resnet34', 'resnet50', 'resnet101',
           'resnet152', 'resnext50_32x4d', 'resnext101_32x8d',
           'wide_resnet50_2', 'wide_resnet101_2']


model_urls = {
    'resnet18': 'https://download.pytorch.org/models/resnet18-f37072fd.pth',
    'resnet34': 'https://download.pytorch.org/models/resnet34-b627a593.pth',
    'resnet50': 'https://download.pytorch.org/models/resnet50-0676ba61.pth',
    'resnet101': 'https://download.pytorch.org/models/resnet101-63fe2227.pth',
    'resnet152': 'https://download.pytorch.org/models/resnet152-394f9c45.pth',
    'resnext50_32x4d': 'https://download.pytorch.org/models/resnext50_32x4d-7cdf4587.pth',
    'resnext101_32x8d': 'https://download.pytorch.org/models/resnext101_32x8d-8ba56ff5.pth',
    'wide_resnet50_2': 'https://download.pytorch.org/models/wide_resnet50_2-95faca4d.pth',
    'wide_resnet101_2': 'https://download.pytorch.org/models/wide_resnet101_2-32ee1156.pth',
}


def conv3x3(in_planes: int, out_planes: int, stride: int = 1, groups: int = 1, dilation: int = 1) -> nn.Conv2d:
    """3x3 convolution with padding"""
    return nn.Conv2d(in_planes, out_planes, kernel_size=3, stride=stride,
                     padding=dilation, groups=groups, bias=False, dilation=dilation)


def conv1x1(in_planes: int, out_planes: int, stride: int = 1) -> nn.Conv2d:
    """1x1 convolution"""
    return nn.Conv2d(in_planes, out_planes, kernel_size=1, stride=stride, bias=False)

class Hsigmoid(nn.Module):
    def __init__(self, inplace=True):
        super(Hsigmoid, self).__init__()
        self.inplace = inplace

    def forward(self, x):
        return F.relu6(x + 3., inplace=self.inplace) / 3.

class SEModule(nn.Module):
    def __init__(self, channel, reduction=16):
        super(SEModule, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.fc = nn.Sequential(
            nn.Linear(channel, channel // reduction, bias=False),
            nn.ReLU(inplace=True),
            nn.Linear(channel // reduction, channel, bias=False),
            Hsigmoid()
        )

    def forward(self, x):
        b, c, _, _ = x.size()
        y = self.avg_pool(x).view(b, c)
        y = self.fc(y).view(b, c, 1, 1)
        return x * y.expand_as(x)

class GradReverse(Function):
    #@staticmethod
    #def __init__(self, lambd):
    #    self.lambd = lambd
    @staticmethod
    def forward(grev, x, lmbd):
        #self.lmbd = lmbd
        grev.lmbd = lmbd
        return x.view_as(x)

    @staticmethod
    def backward(grev, grad_output):
        #print (grev.lmbd)
        return (grad_output*-grev.lmbd), None
def grad_reverse(x,lambd=1.0):
    return GradReverse.apply(x,lambd)

class BasicBlock(nn.Module):
    expansion: int = 1

    def __init__(
        self,
        inplanes: int,
        planes: int,
        stride: int = 1,
        downsample: Optional[nn.Module] = None,
        groups: int = 1,
        base_width: int = 64,
        dilation: int = 1,
        norm_layer: Optional[Callable[..., nn.Module]] = None
    ) -> None:
        super(BasicBlock, self).__init__()
        if norm_layer is None:
            norm_layer = nn.BatchNorm2d
        if groups != 1 or base_width != 64:
            raise ValueError('BasicBlock only supports groups=1 and base_width=64')
        if dilation > 1:
            raise NotImplementedError("Dilation > 1 not supported in BasicBlock")
        # Both self.conv1 and self.downsample layers downsample the input when stride != 1
        self.conv1 = nn.Conv2d(inplanes, planes, kernel_size=1, bias=False)
        self.bn1 = nn.BatchNorm2d(planes)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=stride,
                               padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(planes)
        self.downsample = downsample
        self.stride = stride
        inp, oup = inplanes, planes * 4
        self.squeeze = inp // 16
        self.dim = int(math.sqrt(inp))
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.fc = nn.Sequential(
            nn.Linear(inp, self.squeeze, bias=False),
            nn.ReLU(inplace=True),
            nn.Linear(self.squeeze, 4, bias=False),
        )
        self.sf = nn.Softmax(dim=1)
        self.conv_s1 = nn.Conv2d(planes, planes, 1, stride=stride, padding=0, bias=False)
        self.conv_s2 = nn.Conv2d(planes, planes, 1, stride=stride, padding=0, bias=False)
        self.conv_s3 = nn.Conv2d(planes, planes, 1, stride=stride, padding=0, bias=False)
        self.conv_s4 = nn.Conv2d(planes, planes, 1, stride=stride, padding=0, bias=False)
        
    def forward(self, x):
        b, c, h, w = x.size()
        y = self.fc(self.avg_pool(x).view(b, c)).view(b, 4, 1, 1, 1)
        y = self.sf(y)
        
        identity = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)
        
        dyres = self.conv_s1(out)*y[:,0] + self.conv_s2(out)*y[:,1] + \
            self.conv_s3(out)*y[:,2] + self.conv_s4(out)*y[:,3]
        out = dyres + self.conv2(out)
        out = self.bn2(out)

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
        out = self.relu(out)

        return out

class ResNet(nn.Module):

    def __init__(
        self,
        block: Type[Union[BasicBlock]],
        layers: List[int],
        num_classes: int = 1000,
        zero_init_residual: bool = False,
        groups: int = 1,
        width_per_group: int = 64,
        replace_stride_with_dilation: Optional[List[bool]] = None,
        norm_layer: Optional[Callable[..., nn.Module]] = None
    ) -> None:
        super(ResNet, self).__init__()
        if norm_layer is None:
            norm_layer = nn.BatchNorm2d
        self._norm_layer = norm_layer

        self.inplanes = 64
        self.dilation = 1
        if replace_stride_with_dilation is None:
            # each element in the tuple indicates if we should replace
            # the 2x2 stride with a dilated convolution instead
            replace_stride_with_dilation = [False, False, False]
        if len(replace_stride_with_dilation) != 3:
            raise ValueError("replace_stride_with_dilation should be None "
                             "or a 3-element tuple, got {}".format(replace_stride_with_dilation))
        self.groups = groups
        self.base_width = width_per_group
        self.conv1 = nn.Conv2d(3, self.inplanes, kernel_size=7, stride=2, padding=3,
                               bias=False)
        self.bn1 = norm_layer(self.inplanes)
        self.relu = nn.ReLU(inplace=True)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
        self.layer1 = self._make_layer(block, 64, layers[0])
        self.layer2 = self._make_layer(block, 128, layers[1], stride=2,
                                       dilate=replace_stride_with_dilation[0])
        self.layer3 = self._make_layer(block, 256, layers[2], stride=2,
                                       dilate=replace_stride_with_dilation[1])
        self.layer4 = self._make_layer(block, 512, layers[3], stride=2,
                                       dilate=replace_stride_with_dilation[2])
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(512 * block.expansion, num_classes)

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            elif isinstance(m, (nn.BatchNorm2d, nn.GroupNorm)):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):	
                m.weight.data.normal_(0, 0.01)	
                if m.bias is not None:	
                    m.bias.data.zero_()	
        self.new_param, self.init_param= [], []

        # Zero-initialize the last BN in each residual branch,
        # so that the residual branch starts with zeros, and each residual block behaves like an identity.
        # This improves the model by 0.2~0.3% according to https://arxiv.org/abs/1706.02677
        if zero_init_residual:
            for m in self.modules():
                if isinstance(m, Bottleneck):
                    nn.init.constant_(m.bn3.weight, 0)  # type: ignore[arg-type]
                elif isinstance(m, BasicBlock):
                    nn.init.constant_(m.bn2.weight, 0)  # type: ignore[arg-type]

    def _make_layer(self, block, planes, blocks, stride=1, dilate=False):
        norm_layer = self._norm_layer
        downsample = None
        previous_dilation = self.dilation
        if dilate:
            self.dilation *= stride
            stride = 1
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = nn.Sequential(
                conv1x1(self.inplanes, planes * block.expansion, stride),
                norm_layer(planes * block.expansion),
            )

        layers = []
        layers.append(block(self.inplanes, planes, stride, downsample))
        self.inplanes = planes * block.expansion
        for _ in range(1, blocks):
            layers.append(block(self.inplanes, planes))

        return nn.Sequential(*layers)

    def _forward_impl(self, x: Tensor) -> Tensor:
        # See note [TorchScript super()]
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)

        return x

    def forward(self, x: Tensor) -> Tensor:
        return self._forward_impl(x)


def _resnet(
    arch: str,
    block: Type[Union[BasicBlock]],
    layers: List[int],
    pretrained: bool,
    progress: bool,
    **kwargs: Any
) -> ResNet:
    model = ResNet(block, layers, **kwargs)
    if pretrained:
        state_dict = load_state_dict_from_url(model_urls[arch],
                                              progress=progress)
        model.load_state_dict(state_dict)
    return model


def resnet18(pretrained: bool = False, progress: bool = True, **kwargs: Any) -> ResNet:
    r"""ResNet-18 model from
    `"Deep Residual Learning for Image Recognition" <https://arxiv.org/pdf/1512.03385.pdf>`_.

    Args:
        pretrained (bool): If True, returns a model pre-trained on ImageNet
        progress (bool): If True, displays a progress bar of the download to stderr
    """
    return _resnet('resnet18', BasicBlock, [2, 2, 2, 2], pretrained, progress,
                   **kwargs)


def resnet34(pretrained: bool = False, progress: bool = True, **kwargs: Any) -> ResNet:
    r"""ResNet-34 model from
    `"Deep Residual Learning for Image Recognition" <https://arxiv.org/pdf/1512.03385.pdf>`_.

    Args:
        pretrained (bool): If True, returns a model pre-trained on ImageNet
        progress (bool): If True, displays a progress bar of the download to stderr
    """
    return _resnet('resnet34', BasicBlock, [3, 4, 6, 3], pretrained, progress,
                   **kwargs)
```
